### ISSUE TITLE
VPKEdit does not respect KDE Plasma's "Keyboard accelerators visibility" setting when opening files

### ISSUE THREAD

**Issue by Tiagoquix** [craftablescience/VPKEdit#137] opened 2024-04-30 06:11 UTC
### Describe the Bug

Hi there.

I personally choose to hide keyboard accelerators (mnemonics) on KDE Plasma. This is respected by most of VPKEdit, except when choosing files.

My theme is Breeze, while the app only offers Windows or Fusion theming.

![image](https://github.com/craftablescience/VPKEdit/assets/30274161/606b1cbd-f371-43e1-8971-a73123dbad74)

![image](https://github.com/craftablescience/VPKEdit/assets/30274161/0d773826-f614-4cbf-8b38-90bb624866c8)

If this could be fixed, I would be grateful. Thanks in advance.

### To Reproduce

Explained above.

### Operating System

Fedora Linux 40 KDE

**Comment by craftablescience** [comment] 2024-04-30 06:19
Technically a duplicate of #93

**Closed by craftablescience** 2024-04-30 06:19 UTC
Labels: bug, duplicate
