### ISSUE TITLE
Mount VPKs

### ISSUE THREAD

**Issue by AtomicTEM** [craftablescience/VPKEdit#190] opened 2024-10-31 16:01 UTC
### Describe Your Suggestion

Would be great to be able to mount VPKs so that when opening lets say a VPK with only models, we can still preview how texture will look on it.

**Comment by craftablescience** [comment] 2024-11-02 04:58
Roughly a duplicate of #72, but your interest in this feature is duly noted

**Closed by craftablescience** 2024-11-02 04:58 UTC
Labels: duplicate, enhancement
