### ISSUE TITLE
Open the file when drag and drop in

### ISSUE THREAD

**Issue by sterno900** [craftablescience/VPKEdit#176] opened 2024-09-22 07:22 UTC
### Describe Your Suggestion

Open the file when drag and drop in the window when no other files is currently opened.

https://github.com/user-attachments/assets/b3917de5-5d7d-4196-b8a8-e38ddc7e6bb1

**Comment by craftablescience** [comment] 2024-09-22 07:25
Duplicate of #159, will be in the next release before end of this month

**Closed by craftablescience** 2024-09-22 07:25 UTC
Labels: duplicate, enhancement
