### ISSUE TITLE
Crash when trying to extract files from BSP

### ISSUE THREAD

**Issue by Tiagoquix** [craftablescience/VPKEdit#139] opened 2024-04-30 06:20 UTC
### Describe the Bug

Hi there.

When I try to extract files from a BSP file, the program crashes and only creates a folder with the map name.

I assume this is due to the fact that VPKEdit does not display a ZIP file that is often included with maps because the standard way of compressing files is not very compatible with normal extraction. Therefore, the ZIP included by the author in the map's BSP is used to extract the map normally without any problems.

The ZIP file, however, is not displayed in VPKEdit.
It is possible to confirm its existence using GCFScape, another program that handles VPKs and displays the file correctly.

There is also usually another file besides a ZIP, but I don't remember its extension.

### To Reproduce

Try to extract files from a BSP file.
Crashes.

### Operating System

Fedora Linux 40 KDE

**Comment by craftablescience** [comment] 2024-04-30 06:22
Duplicate of #99 - LZMA compression is unsupported currently, still waiting for the xz fiasco to settle

**Closed by craftablescience** 2024-04-30 06:22 UTC
Labels: bug, duplicate

**Comment by craftablescience** [comment] 2024-04-30 06:30
If you only want to extract the zip file, 7-zip or GCFScape can probably do that for now. I'd rather add support for LZMA compression than add a halfway hack
