### ISSUE TITLE
vpkedit crashes after a bit of time upon starting (Windows 10)

### ISSUE THREAD

**Issue by justaguy31** [craftablescience/VPKEdit#39] opened 2023-12-23 14:36 UTC
I have guessed so by using task manager. It starts as background process. Once it reaches somewhat 10% of my cpu usage (my base speed is 2.4 GHz), it freezes for a split second, then does nothing (0% usage) for a while until it closes itself. I have every Visual C++ version installed on my machine. Both release types (standalone and installer) fail.

**Comment by craftablescience** [comment] 2023-12-24 22:26
Are you using the latest version (3.6.2)?

**Comment by justaguy31** [comment] 2023-12-27 12:14
yep

**Comment by Vinzuerio** [comment] 2023-12-27 13:40
@justaguy31 what windows 10 build do you use? for some reason, mine has vpkedit installed on build 20H2 has working fine with version 3.6.2, Do you have all the VC++ 2015-2022 runtime installed though?

Or this could be GPU/OpenGL related problem

**Comment by craftablescience** [comment] 2023-12-27 16:03
@Vinzuerio makes a good point, if you don't have the 2015-2022 redistributables you can download them [from the install guide for VPKEdit](https://github.com/craftablescience/VPKEdit/blob/main/INSTALL.md)

**Comment by justaguy31** [comment] 2023-12-28 13:53
i have every Visual C++ version as i said. i use Windows 10 version 10.0.19045 build 19045

**Comment by justaguy31** [comment] 2023-12-28 13:53
(22H2)

**Comment by craftablescience** [comment] 2023-12-28 16:24
I have a test VM running that same version and it works fine. Perhaps your graphics card doesn't support OpenGL 3.3? Can you tell me what DX feature levels it supports: https://www.quora.com/How-do-you-find-out-which-version-of-OpenGL-your-graphics-card-supports

**Comment by justaguy31** [comment] 2023-12-29 06:36
12_1, 12_0, 11_1, 11_0, 10_1, 10_0, 9_3, 9_2, 9_1

**Comment by craftablescience** [comment] 2024-01-10 18:59
@justaguy31 do you have any Source 1 games installed? It looks like the application might crash if it detects Steam but cannot find any Source 1 games (patched in dev)

**Comment by justaguy31** [comment] 2024-01-11 17:22
Sadly, I don't. What do you mean by dev?

**Comment by craftablescience** [comment] 2024-01-11 17:50
I mean its fixed in code, and should be a part of the next beta release

**Comment by craftablescience** [comment] 2024-01-12 05:10
Can you test if the standalone version of the latest beta release (4.0.0-beta.3) launches on your computer? It has the fix

**Comment by justaguy31** [comment] 2024-01-13 10:22
Same story. I wonder if I could look myself what's causing the issue.

**Comment by craftablescience** [comment] 2024-01-13 22:43
Damn, I was sure that was it. I'm not sure how to debug Qt programs on Windows, whenever I try it seems like it has trouble binding to the console. Might need a fix in code

**Comment by craftablescience** [comment] 2024-04-04 11:58
Since this issue has been open for a few months with no way for me to reproduce it and apparently no one else experiencing it, I'm going to close this issue. If you or someone else does find out the cause for the crash, just reopen the issue and let me know what the problem is.

**Closed by craftablescience** 2024-04-04 11:58 UTC
Labels: bug, can't reproduce
