### ISSUE TITLE
VPK Edit saying the file is in use.

### ISSUE THREAD

**Issue by DarkCookieSF** [craftablescience/VPKEdit#146] opened 2024-05-10 00:23 UTC
### Describe the Bug

I opened up a .vpk file from a zip I extracted. Whenever I try opening the .vpk it says a game is using it.

### To Reproduce

I don't know how to reproduce it.

### Operating System

Windows 10

**Comment by craftablescience** [comment] 2024-05-10 00:33
Is the vpk open in any other application? (for example, is the archive extractor closed?)

Where did you extract the vpk to, does vpkedit have appropriate permissions to read the file?

**Comment by craftablescience** [comment] 2024-05-16 19:26
Since no further information was provided, I can't reasonably figure out what was happening here. VPKEdit will tell you the file cannot be opened if another application is using the file, so make sure that isn't the case. Closing as I'm unable to reproduce the issue (and you apparently can't either if I'm reading the issue correctly).

**Closed by craftablescience** 2024-05-16 19:26 UTC
Labels: bug, can't reproduce
