### ISSUE TITLE
Wont export some folders and files.

### ISSUE THREAD

**Issue by person6423** [craftablescience/VPKEdit#167] opened 2024-08-23 20:43 UTC
### Describe the Bug

everytime I try to export the root folder, it slacks and only exports a few folders with very little files in them, then shows an error message explaining that I need permission to save to the save directory, I have tried everything, I gave it modify and write permissions, gave it admin privileges, but had no effect.

### To Reproduce

1. open any vpk folder
2. export the root
3. some folders dont get exported and the message pops up.

### Operating System

Windows 11 Home

**Comment by craftablescience** [comment] 2024-08-23 20:50
Where are you extracting to? I just tried this and it works

**Comment by craftablescience** [comment] 2024-08-24 10:32
Closing, I can't reproduce this issue. Please make sure to extract files to a directory that you have permission to write to (i.e. not in program files).

**Closed** 2024-08-24 10:32 UTC
Labels: bug, can't reproduce

**Comment by person6423** [comment] 2024-08-24 13:48
i'm extracting to my desktop

**Comment by craftablescience** [comment] 2024-08-24 20:17
Did you copy the VPK "dir" file anywhere? VPKEdit won't be able to read its contents without the ancillary archive files.

**Comment by person6423** [comment] 2024-08-25 17:26
sorry but whats the 'dir' file? and what does ancillary mean?
im extracting 'pak01_dir.vpk' from 'steamapps/common/Portal 2/portal2' if that helps. I've noticed with other vpks or mods, VPKEdit works just fine if that also helps.

**Comment by ashifolfi** [comment] 2024-08-25 18:59
> sorry but whats the 'dir' file? and what does ancillary mean? im extracting 'pak01_dir.vpk' from 'steamapps/common/Portal 2/portal2' if that helps. I've noticed with other vpks or mods, VPKEdit works just fine if that also helps.
@person6423 

So in order to keep total file sizes down, the VPK format allows for creating what's known as a "multi-chunk VPK". The way these multi-chunk VPKs work is the following.

- `pak01_dir.vpk` - contains a list of files, but no file data
- `pak01_<number>.vpk` - contains a partial set of file data

<p align="center">
<img src="https://github.com/user-attachments/assets/a1333f6c-b180-4b57-b884-a9485990623a"/>
<i>visual diagram for some assistance</i>
</p>
<br>

The numerical files are what are being referred to by "ancillary files". The dir file is thus self explanatory, being the "_dir.vpk" file.

The file data contained within the complete VPK can only be accessed correctly through the dir file, and only if all chunks (the numerical named files) are present alongside the dir file in the same place.

Think of it as a split archive of sorts.

Someone more familiar with the format could probably answer with a bit more clarity than me but this should be sufficient for the most part in explaining what is meant by that.
